# Generated by Django 3.2.6 on 2021-08-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('contact_method', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
