# Generated by Django 3.2.6 on 2021-08-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('interest', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('pros', models.CharField(max_length=100)),
                ('cons', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('responsibilities', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
                ('five_steps', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('years_experience_required', models.CharField(max_length=100)),
                ('role_list_url', models.CharField(max_length=100)),
                ('listing_source', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('latest_activity', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom.activity')),
            ],
        ),
    ]
