# Generated by Django 3.2.6 on 2021-08-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0002_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='five_steps',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='latest_activity',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='listing_source',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='role_list_url',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='years_experience_required',
        ),
    ]
