# Generated by Django 3.2.6 on 2021-08-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_auto_20210823_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='interest',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='notes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
