# Generated by Django 3.2.6 on 2021-08-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0005_company_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
