# Generated by Django 3.2.6 on 2021-08-26 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloom', '0007_rename_buisness_structure_company_business_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='contact_method',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_contact_through',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='notes',
        ),
        migrations.AddField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='business_structure',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Non_Profit', 'Non_Profit')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='glassdoor_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='interested',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
