# Generated by Django 3.2.6 on 2021-08-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0010_auto_20210826_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloom.company'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contacts',
            field=models.ManyToManyField(to='bloom.Contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='listing_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='rating',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='role_list_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('read_job_description', 'Read Job Description'), ('researched_company', 'Researched Company'), ('optimized_resume_for_role', 'Optimized Resume'), ('in_contact', 'In Contact'), ('applied', 'Applied'), ('interviewed', 'Interviewed'), ('negotiated', 'Negotiated'), ('accepted_offer', 'Accepted Offer'), ('decided_to_pass', 'Decided to Pass'), ('no_offer_extended', 'No Offer Extended')], default='started', max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='years_experience_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
