# Generated by Django 3.2.6 on 2021-08-26 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloom', '0013_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloom.company'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='bloom.Contact'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloom.opportunity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='bloom.Contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
