# Generated by Django 3.2.6 on 2021-08-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0015_auto_20210826_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloom.opportunity'),
        ),
    ]
