# Generated by Django 3.2.6 on 2021-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0016_auto_20210827_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='role_list_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
