# Generated by Django 3.2.6 on 2021-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0017_auto_20210829_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='glassdoor_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5),
        ),
    ]
