# Generated by Django 3.2.6 on 2021-08-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0019_alter_company_glassdoor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Read Job Description', 'Read Job Description'), ('Researched Company', 'Researched Company'), ('Optimized Resume for Role', 'Optimized Resume'), ('In Contact', 'In Contact'), ('Applied', 'Applied'), ('Interviewed', 'Interviewed'), ('Negotiated', 'Negotiated'), ('Accepted Offer', 'Accepted Offer'), ('Decided to Pass', 'Decided to Pass'), ('No Offer Extended', 'No Offer Extended')], default='Started', max_length=100),
        ),
    ]
